# 轴的理解

In [1]:
import numpy as np

In [4]:
arr = np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

轴图像如下  
![](images/numpy_axis.png)

可以看到，对那个轴操作，就如图沿轴方向计算

In [7]:
np.mean(arr,axis=0)

array([4., 5., 6.])

In [8]:
np.mean(arr,axis=1)

array([2., 5., 8.])

In [9]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [10]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

三维的轴较复杂，现在基本还遇不到，以后遇到在进行学习