In [1]:
import numpy as np

# 1.numpy 基本操作

## 1.1列表转矩阵

In [2]:
array = np.array([
    [1,3,5],
    [4,6,9]
])
array

array([[1, 3, 5],
       [4, 6, 9]])

## 1.2基本属性

In [3]:
print('number of dim:',array.ndim) #维度
print('shape:',array.shape) #行列数
print('size:',array.size) #元素个数
print('item:',array.item)

number of dim: 2
shape: (2, 3)
size: 6
item: <built-in method item of numpy.ndarray object at 0x00000247BF5FBB20>


# 2.numpy创建array

In [4]:
#一维array
one = np.array([2,3,4],dtype=np.int32)
print("one:",one)
print("type of one:",one.dtype)

one: [2 3 4]
type of one: int32


In [5]:
#多维数组
two = np.array([
    [1,2,3],
    [4,5,6]
])
print(two)

[[1 2 3]
 [4 5 6]]


In [6]:
#0数组
zero = np.zeros((3,4))
print(zero)
zero1 = np.zeros(3)
print('一维：',zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
一维： [0. 0. 0.]


In [7]:
#1数组
one = np.ones((3,4))
print(one)
one1 = np.ones(3)
print('一维：',one1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
一维： [1. 1. 1.]


In [8]:
#空数组
empty = np.empty((3,4))
print(empty)
empty1 = np.empty(3)
print('一维：',empty1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
一维： [1. 1. 1.]


In [9]:
#连续数组
continuous = np.arange(1,10,1)
continuous

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
#形状改变
continuous.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3.基本运算

## 3.1一维数组运算

In [12]:
a = np.array([5,6,7,8])
b = np.array([1,2,3,4])
c = a - b
print(c)

[4 4 4 4]


In [13]:
a * b #对应相乘 , 加减乘除都是对应元素运算

array([ 5, 12, 21, 32])

In [14]:
np.dot(a,b) #一维数组用矩阵乘法=內积

70

In [15]:
b ** 2  #乘方

array([ 1,  4,  9, 16], dtype=int32)

In [16]:
b ** a #对应元素乘方

array([    1,    64,  2187, 65536], dtype=int32)

In [17]:
np.sin(b) #许多数学函数工具

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [18]:
b < 2

array([ True, False, False, False])

In [19]:
a = np.array([1,1,4,3])
b = np.arange(4)
a == b

array([False,  True, False,  True])

## 3.2多维矩阵运算

In [20]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))
a

array([[1, 1],
       [0, 1]])

In [21]:
b

array([[0, 1],
       [2, 3]])

In [22]:
a.dot(b)

array([[2, 4],
       [2, 3]])

In [23]:
np.dot(a,b)

array([[2, 4],
       [2, 3]])

In [24]:
a * b #对应相乘 , 加减乘除都是对应元素运算

array([[0, 1],
       [0, 3]])

In [25]:
a ** b #对应元素乘方

array([[1, 1],
       [0, 1]], dtype=int32)

In [26]:
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [27]:
np.min(c)

1

In [28]:
np.max(c)

9

In [29]:
np.mean(c) #均值

5.0

In [30]:
np.sum(c)

45

In [31]:
#使用axis 可对 对应行或列进行运算
# 当axis的值为0的时候，将会以列作为查找单元，
#当axis的值为1的时候，将会以行作为查找单元。
np.sum(c,axis=0)

array([12, 15, 18])

In [32]:
np.sum(c,axis=1)

array([ 6, 15, 24])

In [33]:
np.max(c,axis=1)

array([3, 6, 9])

In [34]:
np.argmin(c) #最小值索引

0

In [35]:
np.median(c) #中位数

5.0

In [36]:
c.T #转置

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
np.transpose(c)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

clip(Array,Array_min,Array_max)

将Array_min<X<Array_max X表示矩阵A中的数，如果满足上述关系，则原数不变。

否则，如果X<Array_min，则将矩阵中X变为Array_min;

如果X>Array_max，则将矩阵中X变为Array_max.

In [38]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.clip(c,3,7)

array([[3, 3, 3],
       [4, 5, 6],
       [7, 7, 7]])

## 4.索引与切片

In [40]:
a = np.arange(2,14)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [41]:
a[3] #下标从0开始

5

In [42]:
b = a.reshape(3,4)
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [43]:
b[2]

array([10, 11, 12, 13])

In [44]:
b[1][1]

7

In [45]:
b[0,2]

4

In [46]:
b[1,1:3] #list切片操作

array([7, 8])

In [47]:
for i in b:
    print(i)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [48]:
for i in b.T:  #打印列
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [49]:
#多维转一维
print(a.flatten()) # flat是一个迭代器，本身是一个object属性

[ 2  3  4  5  6  7  8  9 10 11 12 13]


In [50]:
for item in a.flat:
    print(item)

2
3
4
5
6
7
8
9
10
11
12
13


## 5.数组合并

In [51]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))
# vertical stack 上下合并,对括号的两个整体操作。

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
# horizontal stack左右合并
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

### 5.1 数组转矩阵

In [53]:
a[np.newaxis,:]

array([[1, 2, 3]])

In [54]:
a.shape

(3,)

In [55]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [56]:
a[np.newaxis,:].shape #(3,) ->(1, 3)

(1, 3)

In [57]:
c = np.matrix(a)

In [58]:
c.shape

(1, 3)

In [59]:
c 

matrix([[1, 2, 3]])

In [60]:
d = np.zeros(3,)
nd = np.matrix(d)

In [61]:
d.shape

(3,)

In [62]:
nd.shape

(1, 3)

In [63]:
nd

matrix([[0., 0., 0.]])

In [64]:
a.T  #.T对一维数组没用

array([1, 2, 3])

In [65]:
np.array([a]) #转二维矩阵可以转置

array([[1, 2, 3]])

In [66]:
np.array([a]).T

array([[1],
       [2],
       [3]])

## 5.2 多个矩阵合并

In [67]:
a = np.array([1,1,1])
b = np.array([2,2,2])

In [68]:
a

array([1, 1, 1])

In [69]:
b

array([2, 2, 2])

In [70]:
a = np.matrix(a)
b = np.matrix(b)

In [71]:
a

matrix([[1, 1, 1]])

In [72]:
b

matrix([[2, 2, 2]])

In [73]:
np.concatenate((a,b),axis = 0) #纵向合并

matrix([[1, 1, 1],
        [2, 2, 2]])

In [74]:
np.concatenate((a,b),axis = 1) #横向合并

matrix([[1, 1, 1, 2, 2, 2]])

In [75]:
np.concatenate((a,a,b,b),axis = 0)

matrix([[1, 1, 1],
        [1, 1, 1],
        [2, 2, 2],
        [2, 2, 2]])

# 6.array分割

In [76]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
# 等量分割
np.split(a,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [78]:
# 等量分割 默认axis = 0
np.split(a,3) #按纵向分割成3份

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [79]:
# 非等量分割
np.array_split(a,3,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [80]:
np.vsplit(a,3) # 横向

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [81]:
np.hsplit(a,2) #纵向

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

# 7.numpy.copy 与 =

In [82]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [83]:
# =具有关联性 浅复制
b = a 
c = a

In [84]:
b

array([0, 1, 2, 3])

In [85]:
c

array([0, 1, 2, 3])

In [86]:
a[0] = 11
b

array([11,  1,  2,  3])

In [87]:
c

array([11,  1,  2,  3])

In [88]:
b is a

True

In [89]:
c is a 

True

In [90]:
b[1:3] = [22,33]
a

array([11, 22, 33,  3])

In [91]:
#copy 深复制
a = np.arange(4)
b = a.copy()
b

array([0, 1, 2, 3])

In [92]:
a[0] = 11
b

array([0, 1, 2, 3])

In [93]:
a

array([11,  1,  2,  3])

# 8.广播机制 

numpy数组间的基础运算是一对一，也就是a.shape==b.shape，但是当两者不一样的时候，就会自动触发广播机制，如下例子：

In [94]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


这里以tile模拟上述操作，来回到a.shape==b.shape情况！

In [95]:
# 对[0,1,2]行重复3次，列重复1次
b = np.tile([0,1,2],(4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [96]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

![](images/1.png)
![](images/2.png)

是不是任何情况都可以呢？

当然不是，只有当两个数组的trailing dimensions  compatible时才会触发广播，否则报错ValueError: frames are not aligned exception。

上面表达意思是尾部维度必须兼容！

# 9.常用函数

In [97]:
x = np.array([1,2,3,4,3,0,1])
np.bincount(x)

array([1, 2, 1, 2, 1], dtype=int64)

统计索引出现次数：索引0出现1次，1出现2次，2出现1次，3出现2次，4出现1次

因此通过bincount计算出索引出现次数如下：

上面怎么得到的？

对于bincount计算吗，bin的数量比x中最大数多1，例如x最大为4，那么bin数量为5(index从0到4)，也就会bincount输出的一维数组为5个数，bincount中的数又代表什么？代表的是它的索引值在x中出现的次数！

函数原型为：numpy.argmax(a, axis=None, out=None).

函数表示返回沿轴axis最大值的索引。

In [107]:
x = [
    [1,3,3],
    [7,5,2]
]
np.argmax(x)

3

对于这个例子我们知道，7最大，索引位置为3(这个索引按照递增顺序)！从0开始递增

axis属性

axis=0表示按行操作，也就是对比当前列，找出最大值的索引！

In [108]:
np.argmax(x,axis=0)

array([1, 1, 0], dtype=int64)

In [109]:
np.argmax(x,axis=1)

array([1, 0], dtype=int64)

In [110]:
x = np.array([1, 3, 2, 3, 0, 1, 0]) #重复最大元素，返回第一个最大值索引
x.argmax()

1

In [114]:
np.around([-0.6,1.2798,2.357,9.67,13], decimals=0)#取指定位置的精度 负数进位取绝对值大的！

array([-1.,  1.,  2., 10., 13.])

In [115]:
np.around([1.2798,2.357,9.67,13], decimals=1)

array([ 1.3,  2.4,  9.7, 13. ])

In [120]:
np.around([1.279845,2.357,9.67,13], decimals=2)

array([ 1.28,  2.36,  9.67, 13.  ])

In [122]:
np.around([1.25,2.357,9.67,13], decimals=1)

array([ 1.2,  2.4,  9.7, 13. ])

从上面可以看出，decimals表示指定保留有效数的位数，当超过5就会进位(不包含5)！

In [123]:
x = np.arange(1 , 16).reshape((3 , 5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [125]:
np.diff(x)  #默认axis=1  离散差值  就是后一个元素减去前一个元素。

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [126]:
np.diff(x,axis=0)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [127]:
np.floor([-0.6,-1.4,-0.1,-1.8,0,1.4,1.7]) #取整，负数取整，跟上述的around一样，是向左！

array([-1., -2., -1., -2.,  0.,  1.,  1.])

In [128]:
np.ceil([1.2,1.5,1.8,2.1,2.0,-0.5,-0.6,-0.3]) #取上限

array([ 2.,  2.,  2.,  3.,  2., -0., -0., -0.])

利用np.where实现小于0的值用0填充吗，大于0的数不变！

In [129]:
x = np.array([[1, 0],
       [2, -2],
     [-2, 1]])
x

array([[ 1,  0],
       [ 2, -2],
       [-2,  1]])

In [130]:
np.where(x>0,x,0)

array([[1, 0],
       [2, 0],
       [0, 1]])